receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    labels:
      service: tao-dividends

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [loki] 